### ISSUE TITLE
有docker镜像吗

### ISSUE THREAD

**Issue by meng-fucius** [yoimiya-kokomi/Miao-Yunzai#40]
想把原来的yunzai换成喵喵版  之前使用docker compose部署的 喵喵版有构建好的镜像嘛

**Comment by Mateoust** [comment]
自己构建一个镜像就好。在项目这里有个[Dockerfile](https://github.com/yoimiya-kokomi/Miao-Yunzai/blob/master/docker/Dockerfile)
git clone项目到你本地。然后安装好docker
使用`cd miao-yunzai/docker/`进到目录里
再使用`docker build -t yoimiya-kokomi/miao-yunzai:v3plus .`（注意尾部的点）
在使用`docker image ls`就能看到镜像了。然后使用docker compose部署即可，记得修改一下docker-compose.yaml里面使用的镜像名
例如：
```
version: "3.9"
services:
  yunzai-bot:
    container_name: yunzai-bot
    image: yoimiya-kokomi/miao-yunzai:v3plus
    restart: always
    volumes:
      - ./yunzai/config:/app/Yunzai-Bot/config/config/ # 配置文件
      - ./yunzai/genshin_config:/app/Yunzai-Bot/plugins/genshin/config # 配置文件
      - ./yunzai/logs:/app/Yunzai-Bot/logs # 日志文件
      - ./yunzai/data:/app/Yunzai-Bot/data # 数据文件
      - ./yunzai/plugins/example:/app/Yunzai-Bot/plugins/example # js 插件
      # 以下目录是插件目录，安装完插件后需要手动添加映射
      - ./yunzai/plugins/miao-plugin:/app/Yunzai-Bot/plugins/miao-plugin                  # 喵喵插件
      - ./yunzai/plugins/yenai-plugin:/app/Yunzai-Bot/plugins/yenai-plugin                  # 椰奶插件
      # - ./yunzai/plugins/py-plugin:/app/Yunzai-Bot/plugins/py-plugin                      # 新py插件
      # - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/Yunzai-Bot/plugins/xiaoyao-cvs-plugin    # 图鉴插件
    depends_on:
      redis: { condition: service_healthy }

  redis:
    container_name: yunzai-redis
    image: redis:alpine
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      start_period: 10s
      interval: 5s
      timeout: 1s
```
